#!/bin/sh

. utilities/bootstrap.sh

ask "The name for this guest?" name "$(parameter 1 "$@")"
ask "The arch to use?" arch $(guess_arch)

echo "name=$name"
echo "arch=$arch"
exit

suite=lucid
packages="dhcp3-client,gpgv,sudo,iputils-ping,apt-utils,ubuntu-keyring,openssh-server"
apt_cache="/192.168.122.1:3142"
mirror="http:/$apt_cache/archive.ubuntu.com/ubuntu"


start_bootstrap "$name"
run  export rootfs="$rootfs"

run  cached-debootstrap     "$suite" "$arch" "$packages" "$mirror"
run  update-locale
run  disable-selinux
run  setup-dhcp-networking  "$name"
run  create-lxc-service
run  fix-ssh-conf
run  lucid-hacks
run  update-openssh-keys
run  create-configuration   "$path" "$name" "$arch"
run  change-password

stop_bootstrap

