#!/bin/sh

. utilities/bootstrap.sh

ask "The name for this guest?" name "$(parameter 1 "$@")"
ask "The arch to use?" arch $(guess_arch)

suite=lucid
packages="dhcp3-client,gpgv,sudo,iputils-ping,apt-utils,ubuntu-keyring,openssh-server"
mirror="http:/$apt_cache/archive.ubuntu.com/ubuntu"


start_bootstrap
run  export rootfs="$rootfs"

run  cached-debootstrap     "$suite" "$arch" "$packages" "$mirror"
run  update-locale
run  disable-selinux
run  setup-dhcp-networking  "$name"
run  create-lxc-service
run  fix-ssh-conf
run  lucid-hacks
run  update-openssh-keys
run  create-configuration   "$path" "$name" "$arch"
run  change-password

stop_bootstrap

