#!/bin/sh

. utilities.sh

# Passing the password in cmdline args is shown by ps -f
# and environment variables are shown by ps e.  Not sure
# if there's any good way for user to supply a password.

echo "NOTE: Root password is 'admin'.  Please change this!"
echo "root:${PASSWORD:-admin}" | chroot . chpasswd

