#!/bin/sh

# Creates /etc/init/lxc.conf.  Without this file, the machine never
# fully boots.  todo: why is it needed?


. utilities/utilities.sh

require rootfs


create "$rootfs/etc/init/lxc.conf" <<EOF
# fake some events needed for correct startup

description     "Container Upstart"

start on startup

script
        rm -rf /var/run/*.pid
        rm -rf /var/run/network/*
        /sbin/initctl emit stopped JOB=udevtrigger --no-wait
        /sbin/initctl emit started JOB=udev --no-wait
end script
EOF
