#!/bin/sh

# sets up networking for dhcp

. utilities.sh

hostname="$1"
require hostname


create "./etc/network/interfaces" <<EOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
EOF

create "./etc/hostname" <<EOF
$hostname
EOF

create "./etc/hosts" <<EOF
127.0.0.1 localhost $hostname
EOF

