#!/bin/sh

# Compiles and creates the proper locale based on the $LANG environment var.

. utilities.sh

if [ -z "$LANG" ]; then
  run chroot . locale-gen en_US.UTF-8
  run chroot . update-locale LANG=en_US.UTF-8
else
  run chroot . locale-gen "$LANG"
  run chroot . update-locale LANG="$LANG"
fi

